### ISSUE TITLE
Not able to install Packages

### ISSUE THREAD

**Issue by ansulagrawal** [Yell0wflash/budbo-website#1]
Hi @Yell0wflash , I love your portfolio so I was trying to run in local but while installing packages I got errors:

![image](https://github.com/Yell0wflash/budbo-website/assets/55939700/c90a846d-1472-413e-9699-2ed2749feb9f)

can you please help me out for installing.

**Comment by VSLuis1** [comment]
npm install --force

**Comment by ansulagrawal** [comment]
Tried didn't work

**Comment by PranayRJuturu** [comment]
Hi @ansulagrawal ! still facing the same issue?

**Comment by ansulagrawal** [comment]
Yea

**Comment by ansulagrawal** [comment]
Yes getting same issue still

**Comment by PranayRJuturu** [comment]
Have you tried removing/uninstalling the node_Modules folder and installing it again?

**Comment by ansulagrawal** [comment]
Yes I tried all possible ways
